[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_solbank_program = "DVNJZ33NMmtUsng1muNqzfnNKcCW2EYbKcH3uAxP7tyC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/satosheep/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
